[phases.setup]
nixPkgs = [
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",
  "harfbuzz",
  "freetype",
  "fontconfig",
  "libxml2",
  "libxslt",
  "python311"  # o "python312" si vas con 3.12
]
