[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
DJANGO_SETTINGS_MODULE = "colegio.settings.prod"

[environments.staging]
DJANGO_SETTINGS_MODULE = "colegio.settings.dev"